### ISSUE TITLE
OpenXR support

### ISSUE THREAD

**Issue by PureTryOut** [marlam/qvr#4]
I wonder if there is any OpenXR support? The README mentions some support for hardware directly but I see no mention of OpenXR anywhere. I'd love to use this (For Bino) in combination with Monado (which provides the hardware support, in my case a Valve Index).

**Comment by marlam** [comment]
There is no OpenXR support yet. The plan is to build OpenXR support based on the existing OpenVR code, but there is no schedule yet.
In case of the Valve Index, OpenVR support (Steam VR SDK) should work too.

**Comment by PureTryOut** [comment]
So, that means this issue should remain open no? Turn it into a feature request :wink: 

Glad to hear it's planned at least! I have no means of running anything other than OpenXR with Monado on my system (running Alpine Linux which uses Musl libc so no chance of running of proprietary stuff outside Flatpak) so I'll just patiently wait for the support.
